import { StyleSheet, useColorScheme } from "react-native";
import { palettes, type Palette } from "./theme";

const createStyles = (colors: Palette) => StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.surface },
  boot: { flex: 1, gap: 14, alignItems: "center", justifyContent: "center", backgroundColor: colors.bg },
  ticker: { height: 32, justifyContent: "center", overflow: "hidden", paddingHorizontal: 12, backgroundColor: colors.surface },
  tickerText: { color: colors.muted, fontSize: 12, fontWeight: "800", letterSpacing: 1.4 },
  mono: { fontSize: 12, fontWeight: "800", letterSpacing: 1.5 },
  connectionPage: { flexGrow: 1, padding: 22, paddingBottom: 50, backgroundColor: colors.bg },
  brandMark: { fontSize: 28, fontWeight: "900" },
  connectionTitle: { marginTop: 4, fontSize: 34, fontWeight: "900", letterSpacing: -1.5 },
  eyebrow: { alignSelf: "flex-start", marginBottom: 18, paddingHorizontal: 8, paddingVertical: 6, borderWidth: 1, borderColor: colors.line, fontSize: 12, fontWeight: "800", letterSpacing: 1 },
  hero: { marginBottom: 16, fontSize: 40, lineHeight: 44, fontWeight: "900", letterSpacing: -2 },
  crossed: { textDecorationLine: "line-through", color: colors.muted },
  highlight: { backgroundColor: colors.selected },
  copy: { marginBottom: 20, maxWidth: 420, fontSize: 13, lineHeight: 19 },
  field: { marginBottom: 14 },
  fieldLabel: { marginBottom: 6, fontSize: 12, fontWeight: "900", letterSpacing: 1.1 },
  input: { minHeight: 46, borderWidth: 2, borderColor: colors.line, paddingHorizontal: 12, backgroundColor: colors.raised, color: colors.text, fontSize: 13 },
  textarea: { minHeight: 220, borderWidth: 2, borderColor: colors.line, padding: 12, backgroundColor: colors.raised, color: colors.text, fontSize: 12, lineHeight: 18 },
  hint: { marginTop: 8, color: colors.muted, fontSize: 12, lineHeight: 18 },
  notice: { marginBottom: 14, borderWidth: 1, borderColor: colors.line, padding: 10, backgroundColor: colors.selected },
  errorNotice: { backgroundColor: colors.raised, borderColor: colors.stop },
  noticeText: { fontSize: 12, fontWeight: "700", lineHeight: 16 },
  action: { borderRadius: 6, minHeight: 46, alignItems: "center", justifyContent: "center", marginTop: 10, borderWidth: 2, borderColor: colors.accent, backgroundColor: colors.accent, paddingHorizontal: 14 },
  actionSecondary: { backgroundColor: colors.surface, borderColor: colors.strong },
  actionText: { color: colors.onAccent, fontSize: 12, fontWeight: "900", letterSpacing: .8 },
  actionSecondaryText: { color: colors.text },
  disabled: { opacity: .5 },
  header: { minHeight: 76, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderBottomWidth: 2, borderBottomColor: colors.line, paddingLeft: 14, backgroundColor: colors.bg },
  headerBrand: { fontSize: 24, fontWeight: "900", letterSpacing: -1 },
  headerMeta: { marginTop: 3, fontSize: 12, fontWeight: "800", letterSpacing: 1 },
  refreshButton: { alignSelf: "stretch", justifyContent: "center", borderLeftWidth: 2, borderLeftColor: colors.line, paddingHorizontal: 16, backgroundColor: colors.selected },
  refreshText: { fontSize: 12, fontWeight: "900" },
  nav: { flexGrow: 0, maxHeight: 62, backgroundColor: colors.bg, borderBottomWidth: 2, borderBottomColor: colors.line },
  navContent: { minWidth: "100%" },
  navItem: { minWidth: 92, minHeight: 60, justifyContent: "center", gap: 4, borderRightWidth: 1, borderRightColor: colors.line, paddingHorizontal: 10 },
  navItemActive: { backgroundColor: colors.surface },
  navIndex: { fontSize: 12, fontWeight: "700" },
  navLabel: { fontSize: 12, fontWeight: "900" },
  navActiveText: { color: colors.text },
  page: { flexGrow: 1, minHeight: "100%", padding: 16, paddingBottom: 80, backgroundColor: colors.bg },
  loader: { marginBottom: 12 },
  pageTitle: { marginBottom: 20, fontSize: 40, lineHeight: 40, fontWeight: "900", letterSpacing: -1.5 },
  statsGrid: { flexDirection: "row", flexWrap: "wrap", marginVertical: 12, borderTopWidth: 1, borderLeftWidth: 1, borderColor: colors.line },
  stat: { width: "50%", minHeight: 82, justifyContent: "space-between", borderRightWidth: 1, borderBottomWidth: 1, borderColor: colors.line, padding: 12 },
  statLabel: { fontSize: 12, fontWeight: "900", letterSpacing: 1 },
  statValue: { fontSize: 28, fontWeight: "900" },
  sectionTitle: { marginTop: 22, marginBottom: 9, borderBottomWidth: 1, borderBottomColor: colors.line, paddingBottom: 7, fontSize: 12, fontWeight: "900", letterSpacing: 1 },
  conversationRow: { minHeight: 66, flexDirection: "row", alignItems: "center", gap: 9, borderBottomWidth: 1, borderBottomColor: colors.line, paddingVertical: 10 },
  conversationSelected: { backgroundColor: colors.selected, paddingHorizontal: 8 },
  rowIndex: { width: 20, fontSize: 12, fontWeight: "800" },
  sourceBadge: { width: 32, height: 32, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: colors.line, backgroundColor: colors.raised },
  sourceText: { fontSize: 12, fontWeight: "900" },
  flex: { flex: 1 },
  rowTitle: { fontSize: 12, fontWeight: "800", lineHeight: 16 },
  meta: { marginTop: 3, color: colors.muted, fontSize: 12, fontWeight: "700", lineHeight: 18, letterSpacing: .25 },
  arrow: { fontSize: 18, fontWeight: "900" },
  buttonRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 14 },
  divider: { height: 1, marginVertical: 18, backgroundColor: colors.surface },
  empty: { borderWidth: 1, borderColor: colors.line, padding: 14, color: colors.muted, fontSize: 12 },
  detailCard: { marginTop: 24, borderWidth: 2, borderColor: colors.line, padding: 14, backgroundColor: colors.raised },
  provenance: { marginTop: 12, paddingLeft: 10, borderLeftWidth: 3, borderLeftColor: colors.lineage },
  detailLabel: { fontSize: 12, fontWeight: "900", letterSpacing: 1 },
  detailTitle: { marginTop: 8, fontSize: 19, fontWeight: "900", lineHeight: 23 },
  claim: { marginBottom: 6, fontSize: 12, lineHeight: 16 },
  message: { marginBottom: 9, borderWidth: 1, borderColor: colors.line, padding: 10, backgroundColor: colors.bg },
  assistantMessage: { backgroundColor: colors.selected },
  messageRole: { marginBottom: 5, fontSize: 12, fontWeight: "900", letterSpacing: 1, textTransform: "uppercase" },
  messageText: { fontSize: 12, lineHeight: 17 },
  fieldRow: { flexDirection: "row", gap: 10 },
  fieldHalf: { flex: 1 },
  switchRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 12, marginVertical: 12, borderWidth: 1, borderColor: colors.line, padding: 12 },
  switchCopy: { flex: 1 },
  switchTitle: { fontSize: 12, fontWeight: "900", letterSpacing: .7 },
  packet: { marginTop: 10, borderWidth: 1, borderColor: colors.line, padding: 12, backgroundColor: colors.raised },
  packetText: { marginTop: 8, fontSize: 12, lineHeight: 18 },
  successCard: { marginTop: 14, borderWidth: 2, borderColor: colors.line, padding: 12, backgroundColor: colors.selected },
  link: { marginTop: 7, fontSize: 12, fontWeight: "700", lineHeight: 18 },
  handoffRow: { minHeight: 66, flexDirection: "row", alignItems: "center", gap: 8, borderBottomWidth: 1, borderBottomColor: colors.line, paddingVertical: 10 },
  revokeButton: { minHeight: 44, justifyContent: "center", borderWidth: 1, borderColor: colors.line, paddingHorizontal: 9, paddingVertical: 7, backgroundColor: colors.raised },
  revokeText: { color: colors.stop, fontSize: 12, fontWeight: "900" },
  connectorRow: { minHeight: 58, flexDirection: "row", alignItems: "center", gap: 10, borderBottomWidth: 1, borderBottomColor: colors.line, paddingVertical: 10 },
  dot: { width: 10, height: 10, borderRadius: 5, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.strong },
  dotOn: { backgroundColor: colors.live },
  disconnectButton: { minHeight: 44, alignItems: "center", justifyContent: "center", borderWidth: 2, borderColor: colors.line, backgroundColor: colors.raised },
  disconnectText: { color: colors.stop, fontSize: 12, fontWeight: "900", letterSpacing: .8 },
});

const darkStyles = createStyles(palettes.dark);
const lightStyles = createStyles(palettes.light);

export function useTheme() {
  const dark = useColorScheme() !== "light";
  return { dark, colors: dark ? palettes.dark : palettes.light, styles: dark ? darkStyles : lightStyles };
}
