import { analyzeConversation } from "../intel/analyze.js";
import type { Conversation, ConversationMessage } from "../types.js";

/**
 * A conversation as a document you can hand to LaTeX and get a PDF from.
 *
 * The reason this exists rather than "export Markdown and let pandoc deal with
 * it": a chat transcript is nearly the worst possible LaTeX input. It is full of
 * unescaped backslashes, underscores in identifiers, dollar signs in shell
 * snippets and percent signs in numbers, any one of which turns a document into
 * a compile error or, worse, silently eats the rest of a line. Handling that is
 * the whole job, so it is done once, here, with a test that asserts every
 * special character survives.
 *
 * The output targets pdflatex, which is what most people have. It compiles under
 * lualatex and xelatex too; on those the inputenc line is unnecessary but
 * harmless.
 */

const PREAMBLE = String.raw`\documentclass[11pt,a4paper]{article}

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[margin=1in]{geometry}
\usepackage{parskip}
\usepackage{fancyvrb}
\usepackage{xcolor}
\usepackage[hidelinks]{hyperref}

\definecolor{lnkzrule}{HTML}{155B48}
\newcommand{\speaker}[1]{\medskip\noindent\textcolor{lnkzrule}{\textbf{#1}}\par\nopagebreak}
`;

export interface LatexOptions {
  /** Put the extracted decisions and open questions before the transcript. */
  includeAnalysis?: boolean;
}

export function toLatex(conversation: Conversation, options: LatexOptions = {}): string {
  const analysis = analyzeConversation(conversation);
  const includeAnalysis = options.includeAnalysis !== false;

  const lines: string[] = [
    `% Generated by LNKZ from conversation ${conversation.id}`,
    `% Source: ${conversation.source.provider}${conversation.source.app ? ` / ${conversation.source.app}` : ""}`,
    "% Compile with: pdflatex <file>.tex",
    "",
    PREAMBLE,
    `\\title{${escapeLatex(conversation.title)}}`,
    `\\author{${authorLine(conversation)}}`,
    `\\date{${escapeLatex(formatDate(conversation.updatedAt))}}`,
    "",
    String.raw`\begin{document}`,
    String.raw`\maketitle`,
    "",
  ];

  if (conversation.summary) {
    lines.push(String.raw`\begin{abstract}`, escapeLatex(conversation.summary), String.raw`\end{abstract}`, "");
  }

  if (includeAnalysis) {
    lines.push(...claimSection("Decisions", analysis.decisions));
    lines.push(...claimSection("Open questions", analysis.openQuestions));
    lines.push(...claimSection("Action items", analysis.actionItems));
  }

  lines.push(String.raw`\section*{Transcript}`, "");
  for (const message of conversation.messages) {
    lines.push(`\\speaker{${escapeLatex(speakerFor(message))}}`);
    lines.push(renderBody(message.content), "");
  }

  if (includeAnalysis && analysis.topics.length) {
    lines.push(
      String.raw`\section*{Topics}`,
      "",
      escapeLatex(analysis.topics.join(", ")),
      "",
    );
  }

  lines.push(String.raw`\end{document}`, "");
  return lines.join("\n");
}

/**
 * Prose is escaped; fenced code is not, because escaping inside a verbatim
 * environment would print the escapes. Splitting on fences first is what makes
 * both true at once.
 */
function renderBody(content: string): string {
  const segments = content.split(/(```[\s\S]*?```)/g).filter((segment) => segment.length > 0);
  const rendered: string[] = [];

  for (const segment of segments) {
    if (segment.startsWith("```")) {
      const body = segment.replace(/^```[^\n]*\n?/, "").replace(/```$/, "").replace(/\s+$/, "");
      if (!body) continue;
      // Verbatim cannot contain its own end marker, and a stray one would break
      // the document rather than the block, so it is neutralized.
      const safe = body.replace(/\\end\{Verbatim\}/g, "\\end {Verbatim}");
      rendered.push(String.raw`\begin{Verbatim}[fontsize=\small,breaklines=true,breakanywhere=true]`, safe, String.raw`\end{Verbatim}`);
      continue;
    }
    const prose = escapeLatex(segment).trim();
    if (prose) rendered.push(prose);
  }

  return rendered.join("\n") || "\\emph{(empty)}";
}

function claimSection(heading: string, claims: { text: string }[]): string[] {
  if (!claims.length) return [];
  return [
    `\\section*{${escapeLatex(heading)}}`,
    "",
    String.raw`\begin{itemize}`,
    ...claims.slice(0, 12).map((claim) => `  \\item ${escapeLatex(claim.text)}`),
    String.raw`\end{itemize}`,
    "",
  ];
}

function authorLine(conversation: Conversation): string {
  const names = conversation.participants.length
    ? conversation.participants
    : [conversation.source.provider];
  return names.map(escapeLatex).join(String.raw` \and `);
}

function speakerFor(message: ConversationMessage): string {
  if (message.author) return message.author;
  return message.role.charAt(0).toUpperCase() + message.role.slice(1);
}

function formatDate(value: string): string {
  const parsed = new Date(value);
  return Number.isNaN(parsed.getTime()) ? value : parsed.toISOString().slice(0, 10);
}

/** The characters LaTeX treats specially, made literal. */
export function escapeLatex(value: string): string {
  // Backslashes are parked on a sentinel first. Every replacement below emits
  // backslashes of its own, so escaping them in place would escape the escapes.
  const SENTINEL = "\u0000";
  return value
    .replace(/\\/g, SENTINEL)
    .replace(/([{}$&#%_])/g, "\\$1")
    .replace(/\^/g, "\\textasciicircum{}")
    .replace(/~/g, "\\textasciitilde{}")
    .split(SENTINEL)
    .join("\\textbackslash{}");
}
